#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libgudev
Version  : 237
Release  : 19
URL      : https://download.gnome.org/sources/libgudev/237/libgudev-237.tar.xz
Source0  : https://download.gnome.org/sources/libgudev/237/libgudev-237.tar.xz
Summary  : GObject bindings for libudev
Group    : Development/Tools
License  : LGPL-2.1
Requires: libgudev-data = %{version}-%{release}
Requires: libgudev-lib = %{version}-%{release}
Requires: libgudev-license = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : gobject-introspection
BuildRequires : gobject-introspection-dev
BuildRequires : gtk-doc-dev
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(libudev)

%description
libgudev
========
This is libgudev, a library providing GObject bindings for libudev. It
used to be part of udev, then merged into systemd. It's now a project
on its own.

%package data
Summary: data components for the libgudev package.
Group: Data

%description data
data components for the libgudev package.


%package dev
Summary: dev components for the libgudev package.
Group: Development
Requires: libgudev-lib = %{version}-%{release}
Requires: libgudev-data = %{version}-%{release}
Provides: libgudev-devel = %{version}-%{release}
Requires: libgudev = %{version}-%{release}

%description dev
dev components for the libgudev package.


%package lib
Summary: lib components for the libgudev package.
Group: Libraries
Requires: libgudev-data = %{version}-%{release}
Requires: libgudev-license = %{version}-%{release}

%description lib
lib components for the libgudev package.


%package license
Summary: license components for the libgudev package.
Group: Default

%description license
license components for the libgudev package.


%prep
%setup -q -n libgudev-237
cd %{_builddir}/libgudev-237

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1629125083
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dtests=disabled \
-Dgtk_doc=false  builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/libgudev
cp %{_builddir}/libgudev-237/COPYING %{buildroot}/usr/share/package-licenses/libgudev/01a6b4bf79aca9b556822601186afab86e8c4fbf
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/GUdev-1.0.typelib
/usr/share/gir-1.0/*.gir
/usr/share/vala/vapi/gudev-1.0.deps
/usr/share/vala/vapi/gudev-1.0.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/gudev-1.0/gudev/gudev.h
/usr/include/gudev-1.0/gudev/gudevclient.h
/usr/include/gudev-1.0/gudev/gudevdevice.h
/usr/include/gudev-1.0/gudev/gudevenumerator.h
/usr/include/gudev-1.0/gudev/gudevenums.h
/usr/include/gudev-1.0/gudev/gudevenumtypes.h
/usr/include/gudev-1.0/gudev/gudevtypes.h
/usr/lib64/libgudev-1.0.so
/usr/lib64/pkgconfig/gudev-1.0.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgudev-1.0.so.0
/usr/lib64/libgudev-1.0.so.0.3.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libgudev/01a6b4bf79aca9b556822601186afab86e8c4fbf
