#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libgudev
Version  : 230
Release  : 4
URL      : http://ftp.gnome.org/pub/gnome/sources/libgudev/230/libgudev-230.tar.xz
Source0  : http://ftp.gnome.org/pub/gnome/sources/libgudev/230/libgudev-230.tar.xz
Summary  : GObject bindings for libudev
Group    : Development/Tools
License  : LGPL-2.1
Requires: libgudev-lib
Requires: libgudev-data
BuildRequires : docbook-xml
BuildRequires : gobject-introspection
BuildRequires : gobject-introspection-dev
BuildRequires : grep
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(libudev)
BuildRequires : sed

%description
General Information
===================
This is libgudev, a library providing GObject bindings for libudev. It
used to be part of udev, then merged into systemd. It's now a project
on its own.

%package data
Summary: data components for the libgudev package.
Group: Data

%description data
data components for the libgudev package.


%package dev
Summary: dev components for the libgudev package.
Group: Development
Requires: libgudev-lib
Requires: libgudev-data
Provides: libgudev-devel

%description dev
dev components for the libgudev package.


%package lib
Summary: lib components for the libgudev package.
Group: Libraries
Requires: libgudev-data

%description lib
lib components for the libgudev package.


%prep
%setup -q -n libgudev-230

%build
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/gir-1.0/GUdev-1.0.gir

%files dev
%defattr(-,root,root,-)
/usr/include/gudev-1.0/gudev/gudev.h
/usr/include/gudev-1.0/gudev/gudevclient.h
/usr/include/gudev-1.0/gudev/gudevdevice.h
/usr/include/gudev-1.0/gudev/gudevenumerator.h
/usr/include/gudev-1.0/gudev/gudevenums.h
/usr/include/gudev-1.0/gudev/gudevenumtypes.h
/usr/include/gudev-1.0/gudev/gudevtypes.h
/usr/lib64/*.so
/usr/lib64/girepository-1.0/GUdev-1.0.typelib
/usr/lib64/pkgconfig/*.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
